scalar Upload

type MutationResult {
  success: Boolean
}

input UserInput {
  email: String
  password: String
}

input MessageInput {
  receiverId: ID
  content: String
}

type Mutation {
  createUser(
    firstName: String!
    lastName: String!
    email: String!
    password: String!
  ): User!
  deleteUser(id: ID!): MutationResult
  logIn(email: String, password: String): String
  uploadImage(file: Upload!, purpose: String): MutationResult
  uploadPostImage(file: Upload!, postId: ID!, purpose: String!): MutationResult
  uploadPostImages(files: [Upload]!, postId: ID!): MutationResult
  createPost(
    mainImageFile: Upload
    additionalImageFiles: [Upload]
    title: String
    text: String
    restrictedTo: String
  ): Post!
  followUser(id: ID): MutationResult
}
