type Query {
  users: [User]!
  posts: [Post]!
  user(id: String): User
  post(id: String): Post
  me: User
  usersByKey(key: String): [User]
  postsByKey(key: String): [Post]
  viewablePosts(restrictedTo: RestrictedTo): [Post]
}
